DROP TABLE [dbo].[SupplyFlower]
DROP TABLE [dbo].[Supply]
DROP TABLE [dbo].[WarehouseFlower]
DROP TABLE [dbo].[Warehouse]
DROP TABLE [dbo].[PlantationFlower]
DROP TABLE [dbo].[Plantation]
DROP TABLE [dbo].[Flower]
DROP DATABASE [FlowerSupplies]

DELETE FROM [dbo].[Flower]
DELETE FROM [dbo].[Plantation]
DELETE FROM [dbo].[PlantationFlower]
DELETE FROM [dbo].[Warehouse]
DELETE FROM [dbo].[WarehouseFlower]
DELETE FROM [dbo].[Supply]
DELETE FROM [dbo].[SupplyFlower]